import { FiUsers, FiFeather, FiMapPin, FiDatabase, FiCalendar, FiPlus, FiTag, FiFileText } from "react-icons/fi";
import PageHeader from "../components/common/PageHeader";
import ActionButton from "../components/common/ActionButton";
import StatCard from "../components/common/StatCard";
import Panel from "../components/common/Panel";
import DataTable from "../components/common/DataTable";
const updates=[{crop:"Rice",market:"Antipolo Public Market",price:"₱45.00",date:"2026-08-24"},{crop:"Rice",market:"Cainta Public Market",price:"₱47.00",date:"2026-08-23"},{crop:"Rice",market:"Binangonan Public Market",price:"₱43.00",date:"2026-08-22"},{crop:"Rice",market:"Taytay Public Market",price:"₱48.00",date:"2026-08-21"},{crop:"Rice",market:"Angono Public Market",price:"₱44.00",date:"2026-08-20"}];
const cols=[{key:"crop",label:"Crop"},{key:"market",label:"Market"},{key:"price",label:"Price/kg"},{key:"date",label:"Date"}];
function Dashboard(){return <><PageHeader title="Admin Dashboard" description="Monitor the information and activity that powers AgriPrice."><ActionButton icon={FiUsers} variant="secondary">MAO Accounts</ActionButton><ActionButton icon={FiPlus}>Add Price</ActionButton></PageHeader><div className="stats-grid"><StatCard label="Registered Farmers" value="4" helper="Active farmer accounts" icon={FiUsers}/><StatCard label="Active Crops" value="8" helper="Currently monitored" icon={FiFeather}/><StatCard label="Active Markets" value="7" helper="Across Rizal" icon={FiMapPin}/><StatCard label="Price Records" value="20" helper="Current records" icon={FiDatabase}/><StatCard label="Updated Today" value="4" helper="Price entries" icon={FiCalendar}/></div><div className="dashboard-grid"><div style={{display:"grid",gap:12}}><Panel title="Recent Price Updates" meta="View all" flush><DataTable columns={cols} rows={updates}/></Panel><Panel title="Quick Actions" meta="Common admin tasks"><div className="quick-grid">{[[FiTag,"Add Price"],[FiFeather,"Add Crop"],[FiMapPin,"Add Market"],[FiFileText,"Generate Report"]].map(([Icon,label])=><div className="quick-action" key={label}><span className="quick-icon"><Icon/></span>{label}</div>)}</div></Panel></div><div style={{display:"grid",gap:12,alignContent:"start"}}><Panel title="Price Trend Overview" meta="Last 5 months"><div style={{height:160,display:"grid",placeItems:"center",color:"#708077",fontSize:12,background:"linear-gradient(to top, #eef7f1, transparent)",borderRadius:8}}>Chart area ready for Recharts or your preferred chart library</div></Panel><Panel title="Recent System Activity" meta="Latest actions"><div className="activity-list">{["Rice price updated","Crop record edited","Market activated","Farmer account activated"].map((item,i)=><div className="activity-item" key={item}><span className="activity-icon"><FiTag/></span><div><div className="activity-title">{item}</div><div className="activity-detail">Sample activity • {i===0?"10 min ago":i===1?"42 min ago":i===2?"2 hrs ago":"Yesterday"}</div></div></div>)}</div></Panel></div></div></>}
export default Dashboard;
